import { TransactionCategory } from "@/types/finance";

const LOCAL_RULES: Record<string, TransactionCategory> = {
  ifood: "alimentacao",
  rappi: "alimentacao",
  "uber eats": "alimentacao",
  restaurante: "alimentacao",
  lanchonete: "alimentacao",
  padaria: "alimentacao",
  pizzaria: "alimentacao",
  burger: "alimentacao",
  cafe: "alimentacao",
  uber: "transporte",
  "99": "transporte",
  taxi: "transporte",
  metro: "transporte",
  onibus: "transporte",
  posto: "transporte",
  shell: "transporte",
  ipiranga: "transporte",
  petrobras: "transporte",
  combustivel: "transporte",
  farmacia: "saude",
  droga: "saude",
  "pague menos": "saude",
  drogasil: "saude",
  raia: "saude",
  carrefour: "mercado",
  extra: "mercado",
  assai: "mercado",
  atacadao: "mercado",
  mercado: "mercado",
  supermercado: "mercado",
  atacarejo: "mercado",
  netflix: "assinaturas",
  spotify: "assinaturas",
  prime: "assinaturas",
  disney: "assinaturas",
  max: "assinaturas",
  "claro tv": "assinaturas",
  amazon: "compras",
  americanas: "compras",
  magazine: "compras",
  magalu: "compras",
  "mercado livre": "compras",
  shopee: "compras",
  shein: "compras",
  renner: "compras",
  riachuelo: "compras",
  hering: "compras",
  tim: "contas",
  vivo: "contas",
  claro: "contas",
  energia: "contas",
  agua: "contas",
  saneamento: "contas",
  internet: "contas",
  aluguel: "moradia",
  condominio: "moradia",
  financiamento: "moradia",
  escola: "educacao",
  faculdade: "educacao",
  curso: "educacao",
  hospital: "saude",
  clinica: "saude",
  dentista: "saude",
  tesouro: "investimentos",
  investimento: "investimentos",
  corretora: "investimentos",
  xp: "investimentos",
  rico: "investimentos",
  salario: "renda",
  "pix recebido": "renda",
  deposito: "renda"
};

export function categorizeLocal(description: string): TransactionCategory {
  const lower = description.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
  for (const [key, category] of Object.entries(LOCAL_RULES)) {
    if (lower.includes(key)) {
      return category;
    }
  }
  return "outros";
}
